/**
 * lccode 构建脚本
 * 使用 bun build --compile 编译单文件可执行程序，跨平台交叉编译
 *
 * 用法：
 *   bun scripts/build.ts          仅编译当前平台
 *   bun scripts/build.ts --all    编译全部平台
 */

import { readFileSync, writeFileSync, rmSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'))
const version = pkg.version

const buildAll = process.argv.includes('--all')

/** 从 .md 模板生成 TS 模块，随单文件产物一起打包 */
function generateTemplates(): void {
  const templatesDir = join(root, 'src', 'agent', 'prompts', 'templates')
  const names = ['system-prompt', 'retry-message', 'parse-hints']
  const entries = names.map(name => {
    const raw = readFileSync(join(templatesDir, `${name}.md`), 'utf-8')
    return `  '${name}': ${JSON.stringify(raw)}`
  })
  const generated = `// AUTO-GENERATED by scripts/build.ts - do not edit manually\n` +
    `// 模板源文件: src/agent/prompts/templates/*.md\n\n` +
    `export const TEMPLATES: Record<string, string> = {\n${entries.join(',\n')}\n}\n`
  writeFileSync(join(root, 'src', 'agent', 'prompts', 'templates.generated.ts'), generated)
  console.log('[build] templates.generated.ts 已生成')
}

/** 生成版本号模块，避免单文件运行时读取 package.json */
function generateVersion(): void {
  const generated = `// AUTO-GENERATED by scripts/build.ts - do not edit manually\n` +
    `// 版本号来源: package.json\n\n` +
    `export const LCCODE_VERSION = ${JSON.stringify(version)}\n`
  writeFileSync(join(root, 'src', 'utils', 'version.generated.ts'), generated)
  console.log(`[build] version.generated.ts 已生成 (${version})`)
}

const TARGETS: Record<string, string> = {
  'bun-windows-x64': 'win32-x64',
  'bun-linux-x64': 'linux-x64',
  'bun-darwin-arm64': 'darwin-arm64',
  'bun-darwin-x64': 'darwin-x64',
}

const currentTarget = `bun-${process.platform}-${process.arch}`
const targets = buildAll
  ? TARGETS
  : { [currentTarget]: TARGETS[currentTarget] ?? `${process.platform}-${process.arch}` }

rmSync(join(root, 'dist'), { recursive: true, force: true })
mkdirSync(join(root, 'dist', 'bin'), { recursive: true })

generateTemplates()
generateVersion()

for (const [bunTarget, label] of Object.entries(targets)) {
  const ext = label.startsWith('win32') ? '.exe' : ''
  const outfile = join(root, 'dist', 'bin', `lccode-${label}${ext}`)
  console.log(`[build] ${bunTarget} -> ${outfile}`)

  const result = Bun.spawnSync(
    [
      'bun',
      'build',
      join(root, 'src', 'cli.tsx'),
      '--compile',
      '--minify',
      `--target=${bunTarget}`,
      `--define:LCCODE_VERSION=${JSON.stringify(version)}`,
      `--outfile=${outfile}`,
    ],
    { cwd: root, stdout: 'inherit', stderr: 'inherit' },
  )
  if (result.exitCode !== 0) process.exit(result.exitCode)
}

// 平台启动器：npm bin 指向此脚本，按当前平台选择二进制执行
const shim = `#!/usr/bin/env node
import { spawn } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const key = \`\${process.platform}-\${process.arch}\`
const ext = process.platform === 'win32' ? '.exe' : ''
const bin = join(__dirname, \`lccode-\${key}\${ext}\`)

try {
  await import('node:fs').then(fs => {
    if (!fs.existsSync(bin)) {
      throw new Error('当前平台无对应二进制')
    }
  })
  const child = spawn(bin, process.argv.slice(2), { stdio: 'inherit' })
  child.on('exit', (code, signal) => {
    if (signal) process.kill(process.pid, signal)
    else process.exit(code ?? 0)
  })
} catch {
  console.error(\`lccode: 当前平台 \${key} 无可用二进制，请重新安装 @lcxyxz/lccode 或使用官方发布的版本\`)
  process.exit(1)
}
`

writeFileSync(join(root, 'dist', 'bin', 'lccode.js'), shim)
// console.log('[build] dist/bin/lccode.js 启动器已生成')
